### ISSUE TITLE
One small correction for your GitHub page

### ISSUE THREAD

**Issue by victoriyaforsythe** [ljlamarche/magcoordmap#1]
Hi Leslie,

Angeline asked me to become a beta tester. 
Please modify your first page with something like this:

git clone https://github.com/ljlamarche/magcoordmap.git
cd magcoordmap
pip install .

Otherwise the pip did not work because it wants the version of magcoordmap. 

Cheers,
Victoriya

**Comment by ljlamarche** [comment]
Done!  Thank you for checking this!!
